// <auto-generated />
using KalkulatorWynajmu.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KalkulatorWynajmu.Migrations
{
    [DbContext(typeof(DatabaseController))]
    [Migration("20221004145004_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KalkulatorWynajmu.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("basePrice")
                        .HasColumnType("real");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carAvaliable")
                        .HasColumnType("int");

                    b.Property<int>("carClass")
                        .HasColumnType("int");

                    b.Property<float>("fuelConsumption")
                        .HasColumnType("real");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Car");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            basePrice = 36.99f,
                            brand = "Skoda",
                            carAvaliable = 10,
                            carClass = 13,
                            fuelConsumption = 5.81f,
                            model = "KAMIQ"
                        },
                        new
                        {
                            Id = 2,
                            basePrice = 69.99f,
                            brand = "BMW",
                            carAvaliable = 1,
                            carClass = 20,
                            fuelConsumption = 10.4f,
                            model = "M3 TOURING"
                        },
                        new
                        {
                            Id = 3,
                            basePrice = 45.99f,
                            brand = "Audi",
                            carAvaliable = 1,
                            carClass = 16,
                            fuelConsumption = 5.6f,
                            model = "A1 Sportback"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
