// <auto-generated />
using System;
using DataAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAcces.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221026182702_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarClass")
                        .HasColumnType("int");

                    b.Property<int>("CarState")
                        .HasColumnType("int");

                    b.Property<float>("FuelConsumption")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 36.99f,
                            Brand = "Skoda",
                            CarClass = 20,
                            CarState = 0,
                            FuelConsumption = 5.81f,
                            Model = "KAMIQ",
                            ProductionDate = new DateTime(2000, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "RZE 12345"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 69.99f,
                            Brand = "BMW",
                            CarClass = 40,
                            CarState = 0,
                            FuelConsumption = 10.4f,
                            Model = "M3 TOURING",
                            ProductionDate = new DateTime(2000, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "RZE 15345"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 45.99f,
                            Brand = "Audi",
                            CarClass = 30,
                            CarState = 0,
                            FuelConsumption = 5.6f,
                            Model = "A1 Sportback",
                            ProductionDate = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "RZE 74812"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 45.99f,
                            Brand = "Audi",
                            CarClass = 30,
                            CarState = 0,
                            FuelConsumption = 5.6f,
                            Model = "A1 Sportback",
                            ProductionDate = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "RZE 74812"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 45.99f,
                            Brand = "Audi",
                            CarClass = 30,
                            CarState = 2,
                            FuelConsumption = 5.6f,
                            Model = "A1 Sportback",
                            ProductionDate = new DateTime(2000, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegistrationNumber = "RZE 74812"
                        });
                });

            modelBuilder.Entity("Domain.CarReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
