// <auto-generated />
using DataAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAcces.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BasePrice")
                        .HasColumnType("real");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarAvaliable")
                        .HasColumnType("int");

                    b.Property<int>("CarClass")
                        .HasColumnType("int");

                    b.Property<float>("FuelConsumption")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 36.99f,
                            Brand = "Skoda",
                            CarAvaliable = 10,
                            CarClass = 2,
                            FuelConsumption = 5.81f,
                            Model = "KAMIQ"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 69.99f,
                            Brand = "BMW",
                            CarAvaliable = 1,
                            CarClass = 4,
                            FuelConsumption = 10.4f,
                            Model = "M3 TOURING"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 45.99f,
                            Brand = "Audi",
                            CarAvaliable = 1,
                            CarClass = 3,
                            FuelConsumption = 5.6f,
                            Model = "A1 Sportback"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
